- pipeline: PS Prod-1
  events:
  - type: PUSH
    refs:
    - refs/heads/master
  no_skip_to_most_recent: true
  fail_on_prepare_env_warning: true
  resources: NANO
  actions:
  - action: composer install
    type: BUILD
    docker_image_name: library/php
    docker_image_tag: "8.4"
    execute_commands:
    - composer validate
    - composer install
    - "# vendor/bin/phpunit"
    setup_commands:
    - echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/buddy.ini
    - apt-get update && apt-get install -y git zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - ""
    - "# php ext gd"
    - apt-get install -y libfreetype6-dev
    - apt-get install -y libjpeg62-turbo-dev
    - apt-get install -y libpng-dev
    - docker-php-ext-configure gd --with-freetype --with-jpeg
    - docker-php-ext-install gd
    - ""
    - "# php ext pdo_mysql"
    - docker-php-ext-configure pdo_mysql --with-pdo-mysql
    - docker-php-ext-install pdo_mysql
    - ""
    - "# php ext zip"
    - apt-get install -y zip
    - apt-get install -y unzip
    - apt-get install -y zlib1g-dev
    - apt-get install -y libzip-dev
    - docker-php-ext-install zip
    shell: BASH
  - action: npm build
    type: BUILD
    docker_image_name: library/node
    docker_image_tag: "22"
    execute_commands:
    - cd web/app/themes/ps2025_theme
    - npm install
    - npm run build
    shell: BASH
  - action: Build DO droplet
    type: DOCTL
    integration: digitalocean
    execute_commands:
    - "doctl compute droplet create ps-staging --size s-1vcpu-1gb --image lemp-20-04 --region nyc1 --ssh-keys ${do_ssh_key} --project-id ${do_project_id} --format PublicIPv4 --enable-backups"
    shell: BASH
  - action: Set TZ and clean up nginx and make host dir
    type: DOCTL
    integration: digitalocean
    execute_commands:
    - ln -sf /usr/share/zoneinfo/America/Phoenix /etc/localtime
    - DEBIAN_FRONTEND=noninteractive
    - rm -f /etc/nginx/sites-available/default
    - rm -f /etc/nginx/sites-available/digitalocean
    - mkdir -p /var/www/html/precisionscience
    retry_interval: 15
    retry_count: 4
    shell: BASH
  - action: Transfer to ps-staging
    type: DIGITAL_OCEAN
    input_type: BUILD_ARTIFACTS
    local_path: /
    remote_path: /var/www/html/precisionscience
    login: root
    host: ps-staging
    env_key: secure!aTokpY7gepM3K4SgVWeJyA==.9MPXqVZ/Un/r/Euqc5eQ4A==
    authentication_mode: ENV_KEY
    integration: digitalocean
  - action: Set up nginx
    type: DOCTL
    integration: digitalocean
    execute_commands:
    - mv /var/www/html/precisionscience/.devcontainer/config/nginx.conf /etc/sites-available/precisionscience
    - ln -s /etc/sites-available/precisionscience /etc/sites-enabled/precisionscience
    - systemctl restart nginx
    retry_interval: 15
    retry_count: 4
    shell: BASH
